---
  kind: pipeline
  type: docker
  name: linux-amd64

  platform:
    arch: amd64
    os: linux

  steps:
  - name: build
    image: golang:1.14.4
    commands:
    - sh scripts/build.sh
    environment:
      GOARCH: amd64
      GOOS: linux

  - name: publish
    image: plugins/docker:18
    settings:
      auto_tag: true # with auto_tag: true, must push tag or master to push docker image.
      auto_tag_suffix: linux-amd64
      dockerfile: docker/Dockerfile.server.linux.amd64
      repo: taoabc/drone-oss
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      event:
      - push
      - tag